hw2 | Introduce scrapper web clients
PonomarevAlexxander/telegram-notifier pull request #4
Opened 2024-02-23 20:52 UTC by PonomarevAlexxander

Adds basic interfaces for scrapper. All interfaces and clients are aimed at fetching updates from web API services.  
Changes include unit tests for basic implementations.

Support for these web services added:
- GitHub.com
- StackOverflow.com

2024-02-29 13:51 UTC, nexen505 requested changes

2024-02-29 13:51 UTC, nexen505 commented on scrapper/src/main/java/edu/java/scrapper/configuration/BeanFactory.java
> +public class BeanFactory {
Косметика: в Spring есть компонент с таким же названием - лучше во избежание путаницы переименовать конфигурацию.

2024-02-29 13:51 UTC, nexen505 commented on scrapper/src/main/java/edu/java/scrapper/client/github/GithubClientBuilder.java
> +        WebClient webClient = WebClient.builder()
Проблема: тут и в соседнем клиенте при таком создании клиента вручную теряются предконфигурированные фреймворком компоненты.

Предложение: добавить при конфигурации зависимость на `WebClient.Builder webClientBuilder` и использовать ее для создания клиента.

2024-02-29 13:51 UTC, nexen505 commented on scrapper/src/main/java/edu/java/scrapper/service/LinkScheduledUpdater.java
> +    @Scheduled(fixedDelayString = "#{@'app-edu.java.scrapper.configuration.ApplicationConfig'.scheduler().interval()}")
Мысль: можно значительно упростить выражение, если воспользоваться знаком `$` для получения конфигурационного свойства приложения по ключу.

2024-02-29 13:51 UTC, nexen505 commented on scrapper/src/main/java/edu/java/scrapper/client/stackoverflow/StackOverflowClient.java
> +    @GetExchange("/2.3/questions/{id}/answers?order=desc&sort=activity&site=stackoverflow")
Косметика: думаю, что кусочек `/2.3` можно перенести в базовый адрес клиента.

2024-02-29 13:51 UTC, nexen505 commented on scrapper/src/main/java/edu/java/scrapper/client/stackoverflow/StackOverflowClientBuilder.java
> +        return proxyFactory.createClient(edu.java.scrapper.client.stackoverflow.StackOverflowClient.class);
Косметика: кажется, тут указание пакетов лишнее.

2024-03-01 07:43 UTC, PonomarevAlexxander commented on scrapper/src/main/java/edu/java/scrapper/service/LinkScheduledUpdater.java
> +    @Scheduled(fixedDelayString = "#{@'app-edu.java.scrapper.configuration.ApplicationConfig'.scheduler().interval()}")
Я пробовал такой вариант, но у меня почему то он некорректно работал. Попробую сделать так еще раз

2024-03-01 07:43 UTC, PonomarevAlexxander commented on scrapper/src/main/java/edu/java/scrapper/client/stackoverflow/StackOverflowClient.java
> +    @GetExchange("/2.3/questions/{id}/answers?order=desc&sort=activity&site=stackoverflow")
Я думал об этом, но решил что в зависимости от версии api может меняться внутренняя логика обработки, поэтому ее выбор лучше оставить на внутреннюю логику приложения. Еще в дальнейшем может быть понадобиться использование каких то методов из старых версий, что привидет к необходимости редактировать базовый url внутри кода

2024-03-01 08:30 UTC, PonomarevAlexxander commented on scrapper/src/main/java/edu/java/scrapper/service/LinkScheduledUpdater.java
> +    @Scheduled(fixedDelayString = "#{@'app-edu.java.scrapper.configuration.ApplicationConfig'.scheduler().interval()}")
```
Encountered invalid @Scheduled method 'update': Invalid fixedDelayString value "10s" - cannot parse into long
```
Если использовать значение из yaml, то необходимо его будет задавать в long, что не совсем удобно, тк значение будет в ms

2024-03-05 12:46 UTC, nexen505 requested changes

2024-03-05 12:46 UTC, nexen505 commented on scrapper/src/main/java/edu/java/scrapper/service/LinkScheduledUpdater.java
> +    @Scheduled(fixedDelayString = "#{@'app-edu.java.scrapper.configuration.ApplicationConfig'.scheduler().interval()}")
Воспользуйся другим форматом строки-свойства `PT10S`: https://www.mscharhag.com/java/iso8601-durations

2024-03-06 09:31 UTC, PonomarevAlexxander commented on scrapper/src/main/java/edu/java/scrapper/service/LinkScheduledUpdater.java
> +    @Scheduled(fixedDelayString = "#{@'app-edu.java.scrapper.configuration.ApplicationConfig'.scheduler().interval()}")
Спасибо, так работает

2024-03-06 12:14 UTC, nexen505 approved these changes

2024-03-08 09:31 UTC, merged