hw3 | Add controller layer
PonomarevAlexxander/telegram-notifier pull request #6
Opened 2024-03-03 10:49 UTC by PonomarevAlexxander

2024-03-08 09:48 UTC, PonomarevAlexxander commented
Сделал ребейз чтобы была адекватная история коммитов, поэтому пришлось сделать еще один пуш, но сами изменения к дз я не менял

2024-03-10 08:25 UTC, nexen505 requested changes

2024-03-10 08:25 UTC, nexen505 commented on bot/src/main/java/edu/java/bot/command/HelpCmd.java
> +@Component
Проблема: команды регистрируются в качестве компонентов, но при этом есть `edu.java.bot.configuration.ApplicationConfig#commands`, что создает двойственность использования инъекции списка компонентов.

Предложение: уйти от использования `edu.java.bot.configuration.ApplicationConfig#commands` в пользу механизмов Spring по инъекции списка компонентов-команд.

2024-03-10 08:25 UTC, nexen505 commented on bot/src/main/java/edu/java/bot/configuration/ApplicationConfig.java
> +    @NotEmpty
Проблема: приложение не запускается из-за этого.

> Description:

Failed to bind properties under 'app' to edu.java.bot.configuration.ApplicationConfig:

    Reason: jakarta.validation.UnexpectedTypeException: HV000030: No validator could be found for constraint 'jakarta.validation.constraints.NotEmpty' validating type 'edu.java.bot.configuration.ApplicationConfig$ScrapperClient'. Check configuration for 'scrapperClient'
Action:
Update your application's configuration

Предложение: восстановить запуск приложения.

2024-03-14 13:49 UTC, nexen505 approved these changes

2024-03-14 15:03 UTC, merged