hw4 | Add postgresql databse and migrations
PonomarevAlexxander/telegram-notifier pull request #8
Opened 2024-03-08 16:55 UTC by PonomarevAlexxander

Adds:
- postgres and liquibase in docker compose
- simple migration scripts for liquibase
- base integration test using testcontainers
and liquibase migrations

2024-03-19 11:23 UTC, nexen505 requested changes

2024-03-19 11:23 UTC, nexen505 commented on bot/src/main/java/edu/java/bot/configuration/ApplicationConfig.java
> +    List<Command> commands() {
Вопрос: не лишние ли тут изменения попали?

Предложение: проверить еще раз содержимое конфигурации.

2024-03-19 11:23 UTC, nexen505 commented on migrations/sql/init_tables.sql
> +create table if not exists chat_link
Проблема: кажется, в таблице не хватает первичного ключа.

Предложение: создать составной первичный ключ по двум колонкам.

2024-03-19 11:23 UTC, nexen505 commented on scrapper/src/test/java/edu/java/scrapper/IntegrationTest.java
> +            Database database = DatabaseFactory.getInstance()
Проблема: ресурс не закрывается.

Предложение: попробовать перенести его в `try-with-resources`.

2024-03-19 11:23 UTC, nexen505 commented on scrapper/src/test/java/edu/java/scrapper/IntegrationTest.java
>          runMigrations(POSTGRES);
Проблема: у меня локально миграции не запускаются.

```

java.lang.ExceptionInInitializerError
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(MethodHandleAccessorFactory.java:103)
	at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:200)
	at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:549)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:250)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:260)
	at org.junit.runners.BlockJUnit4ClassRunner$2.runReflectiveCall(BlockJUnit4ClassRunner.java:309)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
Caused by: java.lang.RuntimeException: org.postgresql.util.PSQLException: Подсоединение по адресу localhost:32770 отклонено. Проверьте что хост и порт указаны правильно и что postmaster принимает TCP/IP-подсоединения.
	at edu.java.scrapper.IntegrationTest.getConnection(IntegrationTest.java:41)
	at edu.java.scrapper.IntegrationTest.runMigrations(IntegrationTest.java:46)
	at edu.java.scrapper.IntegrationTest.<clinit>(IntegrationTest.java:34)
	... 31 more
Caused by: org.postgresql.util.PSQLException: Подсоединение по адресу localhost:32770 отклонено. Проверьте что хост и порт указаны правильно и что postmaster принимает TCP/IP-подсоединения.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:342)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:263)
	at org.postgresql.Driver.makeConnection(Driver.java:443)
	at org.postgresql.Driver.connect(Driver.java:297)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at edu.java.scrapper.IntegrationTest.getConnection(IntegrationTest.java:39)
	... 33 more
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:682)
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:751)
	at org.postgresql.core.PGStream.createSocket(PGStream.java:243)
	at org.postgresql.core.PGStream.<init>(PGStream.java:98)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:132)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:258)
	... 40 more
```

Предложение: уточнить стратегию ожидания старта контейнера (см. `Wait#forListeningPort()`).

2024-03-19 11:58 UTC, PonomarevAlexxander commented on bot/src/main/java/edu/java/bot/configuration/ApplicationConfig.java
> +    List<Command> commands() {
Запутался с конфликтами при ребейзе(

2024-03-19 12:02 UTC, PonomarevAlexxander commented on migrations/sql/init_tables.sql
> +create table if not exists chat_link
Да, я сделал это в следующем PR, забыл что тут не добавлял. Стоит сюда тоже перенести?

2024-03-20 13:12 UTC, nexen505 approved these changes

2024-03-20 14:17 UTC, merged